### ISSUE TITLE
Auto-capture RouteInfo

### ISSUE THREAD

**Issue by simonihmig** [Windvis/ember-breadcrumb-trail#13] opened 2021-05-20 09:42 UTC
Hey, first of all congrats for the addon! 😁 
I like the declarative approach. Thinking about maybe adding a simple wrapper component to `ember-bootstrap` to auto-generate the appropriate Bootstrap markup based on what `{{breadcrumbs}}` returns...

Anyway, to the topic: I feel the addon could be a bit more opinionated about capturing the route parameters, as that is a use case you will always have. The router service exposes the current [`RouteInfo`](https://api.emberjs.com/ember/release/classes/RouteInfo) through [`currentRoute`](https://api.emberjs.com/ember/3.26/classes/RouterService/properties/currentRoute?anchor=currentRoute), which the `{{breadcrumb}}` helper could capture, and expose it by default just like title.

So your Readme's example could look something like this:

```hbs
<nav aria-label="Breadcrumb">
  <ol>
    {{#each (breadcrumbs) as |breadcrumb|}}
      <li>
        <LinkTo
          @route={{breadcrumb.routeInfo.name}}
          @models={{breadcrumb.routeInfo.params}}
          @query{{breadcrumb.routeInfo.queryParams}}
          aria-current={{if (is-last breadcrumb breadcrumbs) "page"}}
        >
          {{breadcrumb.title}}
        </LinkTo>
      </li>
    {{/each}}
  </ol>
</nav>

{{! index.hbs }}
{{breadcrumb "Home"}}

{{! about.hbs }}
{{breadcrumb "About"}}
```

This would hopefully then work ootb also with more complicated routes, with dynamic segments/models and QPs. And it would actually allow my use case of a Bootstrap wrapper, as the `routeInfo` property becomes a public API that others could rely on, whereas otherwise I would need to force users into using *my naming* for those explicit arguments. 

It's probably not quite as easy as it sounds here, because the `{{breadcrumb}}` helper would always see the leaf-most route, even the one that is on `application.hbs`. But the `RouteInfo` is traversable (`.child`/`.parent`), so maybe it's possible to match the stack of RouteInfos to the stack of breadcrumbs? That is assuming your helpers are used exactly in the way the routes are nested, if that's not the case (e.g. you skipped a helper invocation in a sub-route) then this approach probably breaks apart!? 🤔

Idk, just thinking aloud here, but that's thought I wanted to share quickly... :wink:

**Comment by cah-brian-gantzler** [comment] 2021-05-29 03:28
Ok so to continue with just talking out loud. I love the declarative.  I already was thinking along the lines of what you had above here and looking into it I find that the above is doable except as you stated, if you skip a breadcrumb, and I do, there is no way to match unless you also use the @route param on breadcrumb which pretty much defeats the purpose.

In the above, you really only want breadcrumb to define the title, but it could be used for other things in the future. Upon searching even more I find that ember actually already solves this problem, just not declaratively. See [buildRouteInfoMetadata](https://api.emberjs.com/ember/3.26/classes/Route/methods/buildRouteInfoMetadata?anchor=buildRouteInfoMetadata) and EmberMap goes into a whole [blog](https://embermap.com/topics/what-s-new-in-ember/routeinfo-metadata-3-10) about it.

If we could give up on the declarative of  the breadcrumb helper and used the buildRouteInfoMetadata, the entire breadcrumb service would no longer be needed, as the router service via routeInfo would have everything. We would use a breadcrumb key in the metadata as described so if you did skip a route defining that key, everything would still work. 

So I guess the question would be, are we willing to give up on the declarative breadcrumb helper. Actually if you read the blog you will find that a simple getter on the one controller where the breadcrumbs helper would be used just exposing the router.currentRoute does away with the breadCrumbs helper and sadly this entire addon :(

One note though about your above example, you would need to handle the routeInfo params because from the docs `The values of the route's parameters. These are the  same params that are received as arguments to the  route's model hook. Contains only the parameters  valid for this route, if any (params for parent or  child routes are not merged).`   Given that, I would reinstate the breadcrumbs helper from this addon and map/transform information from the router service into a specific api for this addon (allowing for the merging of parent params) thus isolating the consumer from any potential router service future changes. Hopefully just updating this addon would fix all usage instead of each app having to adjust. 

LOL, So I confirmed the need for this addon no longer exists then gave reasons for why this addon should exist, except that its very different that what is there now. 

Lets go a little further, if the breadcrumbs was not a helper but instead a provider component it could also yield the linkTo already formatted if you wanted to use that (At this time because of the way the linkTo Component is implemented I dont think you can yield it, but if they someday made the linkTo a real component, then)

That being said, this addon could actually support both variations breadcrumbs/breadcrumb helper and breadcrumbs component/buildRouteInfoMetadata variation 

I think Ill try to put together a PR that allows for the alternate variation and if its not accepted, could always go for another addon

**Comment by Windvis** [comment] 2021-05-29 08:02
Hey @simonihmig  and @cah-briangantzler! Thank you both for the suggestions! While researching breadcrumb solutions I explored this path but I didn't really like it (for the reasons you already mentioned). I understand the reasoning but I'm not really a big fan of the automagically linking breadcrumbs to routes. I think ember-crumbly is a better fit for that style of usage. And improving / modernizing that addon is probably a better idea then :smile:.

The idea behind this addon is that it's fun to use, but flexible enough to not lock you into certain components / patterns. I prefer using ember-link myself, but I don't want to force that upon users. Some people will probably prefer not installing addons and just keep using good old `<LinkTo>`. The main reason I created this addon is that `@bagaar/ember-breadcrumbs` (which has a similar mindset) doesn't support FastBoot.

I totally get why you want functionality like this from a breadcrumbs addon, but I personally don't envision in like that so I think this isn't the addon you are looking for :smile:.

In any case you can always wrap the helper in a component which contains this route matching logic and passes it into the helper. Or you can create a helper which receives the breadcrumbs array and adds the data there. So (for now) I consider this out of scope for this addon.

**Closed as completed by Windvis** 2021-05-29 08:02 UTC
Labels: wontfix

**Comment by cah-brian-gantzler** [comment] 2021-05-29 15:55
Ember-crumbly is no longer being maintained and would have to get it added to the adopted-addons.  I already have a pending PR to fix the has-block property and was actually looking at this addon to switch to because I did prefer the declarative nature. After researching it though, declarative just doesnt have access to the needed functionality. 

@simonihmig should we pursue getting ember-crumbly to adopted addons. The breadcrumb property on the route was invented before the buildRouteInfoMetadata was available. I would suggest making a breaking changing to what was returned from the breadcrumb property to be returned from the buildRouteInfoMetadata.

**Comment by cah-brian-gantzler** [comment] 2021-06-01 18:32
I understand you closed this issue, but please read, there are revelations. 

None of the current addon implementations are really breadcrumbs and calling it that is part of the confusion. Breadcrumbs keep track of the path you have taken, that means that they only way back is back. Going to another route should add to a breadcrumb not remove them

Ember-crumby (and the work I did on the weekend) are really route hierarchy links. If you go to another branch they reset. Its just shows links for your current route linage. The interesting thing here is, if you only transition up the stack, you actually dont have to pass the model on the link to and the query params are sticky, so you dont have to pass those either. so what @simonihmig what asking for already works as long as you are just going up the stack. The model and query params on the linkTo are only useful when linking to a different parentage.

This addon, is really a dynamic "action bar".   Buttons are added and buttons are removed based on the current templates being show which now makes more sense on why you want a single template to add multiple.  Using the data property you could easily write an if in the container and sometimes show links, sometimes show buttons, whatever. You could ever pass a component in the data and render that. So, basically as long as you only render the crumbs on route templates, you can use a button bar creatively to act like a hierarchy route link bar and it will work without needing to pass the models or query params. 

Given that we now understand that this is a button bar. Adding a property, call it bar, to the crumb and the container, you would with a filter be able to support multiple distinct bars.

Lastly the breadcrumbs as a helper does work, but I would have preferred it more as a provider component. The helper breadcrumb does not actually return anything. While that may work now, I wonder about the future compatibility, provider component here for sure.

So after all I have learned now, this addon does actually fit the use I have, as long as I understand all the implied rules and dont violate them, just have to decide if I should use this, alter the addon I wrote (rename it as it as these addons are not actually breadcrumbs, and alter it a little to reflect what it correctly is doing), or look for a more traditional button bar since creatively I see it also serves the purpose.

Thanks for writing this addon as it sent me down a path of learning :)
